# Generated by Django 4.2.11 on 2026-03-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_marketprice_plant_council_fields"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRequestproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orders.orderrequest",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingListProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orders.shoppinglist",
                    ),
                ),
            ],
            options={
                "unique_together": {("shopping_list", "product")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="shoppinglistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shoppinglistitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shoppinglistitem",
            name="shopping_list",
        ),
        migrations.DeleteModel(
            name="OrderRequestItem",
        ),
        migrations.DeleteModel(
            name="ShoppingListItem",
        ),
    ]
