# Generated by Django 4.2.11 on 2026-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "ממתין לאישור"),
                    ("approved", "אושר"),
                    ("sent", "נשלח לספקים"),
                    ("shipped", "יצא למשלוח"),
                    ("delivered", "נמסר"),
                    ("cancelled", "בוטל"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
