# Generated by Django 4.2.11 on 2026-10-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderbatch_order_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrequest",
            name="deadline_handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
