# version: "3.9"

services:
  app:
    build:
      context: .
      args:
         DEV: True
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - TWILIO_ACCOUNT_SID=AC80a1c5c49e83352af2a5865729a479bd
      - TWILIO_AUTH_TOKEN=83569eeeb70fe07dd8bf088dc9950fd5
      - TWILIO_WHATSAPP_NUMBER=+14155238886

    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
    env_file:
      - .env


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://app:8000
    depends_on:
      - app

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info --schedule /tmp/celerybeat-schedule
    env_file:
      - .env

    depends_on:
      - redis
      - db

volumes:
  dev-db-data:
  dev-static-data:
  frontend_node_modules: