# Generated by Django 4.2.11 on 2026-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.CharField(default="jerusalem", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company_name",
            field=models.CharField(default="Default Company", max_length=255),
        ),
    ]
