# Generated by Django 4.2.11 on 2026-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_active_profile_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('tel_aviv', 'תל אביב'), ('jerusalem', 'ירושלים'), ('haifa', 'חיפה'), ('south', 'דרום'), ('north', 'צפון'), ('center', 'מרכז')], default='jerusalem', max_length=50),
        ),
    ]
