# Generated by Django 4.2.11 on 2026-10-07 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("answered", "נענתה"),
                            ("off_topic", "לא קשורה"),
                            ("error", "שגיאה"),
                            ("round_limit", "חריגה ממספר הסבבים"),
                            ("throttled", "נחסמה (עומס)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_type", models.CharField(blank=True, max_length=100)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("tool_rounds", models.PositiveSmallIntegerField(default=0)),
                ("tools_called", models.JSONField(blank=True, default=list)),
                ("empty_result", models.BooleanField(default=False)),
                ("ambiguous", models.BooleanField(default=False)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[("up", "👍"), ("down", "👎")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
