# Generated by Django 4.2.11 on 2026-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_marketprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="whatsapp_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
