# Generated by Django 4.2.11 on 2026-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_add_min_value_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", 'ק"ג'),
                    ("gram", "גרם"),
                    ("unit", "יחידה"),
                    ("box", "ארגז"),
                    ("liter", "ליטר"),
                    ("meter", "מטר"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
