# Generated by Django 4.2.11 on 2026-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_supplier_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", 'ק"ג'),
                    ("gram", "גרם"),
                    ("unit", "יחידה"),
                    ("box", "ארגז"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
