# Generated by Django 4.2.11 on 2026-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", 'ק"ג'),
                    ("gram", "גרם"),
                    ("unit", "יחידה"),
                    ("box", "ארגז"),
                    ("bundle", "אגודה"),
                    ("pack", "חבילה"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
